name: Build libaacs
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_tools:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [ 'libaacs', 'libbluray', 'libdvdread' ]

    steps:

    - name: Checkout tool
      uses: actions/checkout@v5
      with:
        repository: ShiftMediaProject/${{ matrix.tool }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2 # Action to set up MSBuild environment

    - name: Get dependencies
      run: SMP/project_get_dependencies.bat
      if: matrix.tool != 'libdvdread'

    - name: Build dependencies
      run: msbuild 'SMP/${{ matrix.tool }}_deps.sln' /p:configuration=ReleaseDLL /p:platform=x64

    - name: Build libaacs
      run: msbuild 'SMP/${{ matrix.tool }}.sln' /p:configuration=ReleaseDLL /p:platform=x64

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.tool }}
        path: msvc
