name: Build video libraries for windows
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_tools:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - tool: 'libaacs'
          repo: 'Windows-Media-Tools/libaacs'
        - tool: 'libbdplus'
          repo: 'Windows-Media-Tools/libbdplus'
        - tool: 'libbluray'
          repo: 'Windows-Media-Tools/libbluray'
        - tool: 'libdvdread'
          repo: 'Windows-Media-Tools/libdvdread'

    steps:

    - name: Checkout forked libgpg-error
      uses: actions/checkout@v5
      with:
        repository: Windows-Media-Tools/libgpg-error
        path: libgpg-error
      if: matrix.tool != 'libbluray'

    - name: Checkout forked libgcrypt
      uses: actions/checkout@v5
      with:
        repository: Windows-Media-Tools/libgcrypt
        path: libgcrypt
      if: matrix.tool != 'libbluray'

    - name: Checkout tool
      uses: actions/checkout@v5
      with:
        repository: ${{ matrix.repo }}
        path: ${{ matrix.tool }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3 # Action to set up MSBuild environment

    - name: Get dependencies
      run: ./project_get_dependencies.bat
      working-directory: ${{ matrix.tool }}/SMP
      if: matrix.tool != 'libdvdread'

    - name: Build dependencies
      run: msbuild '${{ matrix.tool }}/SMP/${{ matrix.tool }}_deps.sln' /p:configuration=ReleaseDLL /p:platform=x64 /p:PlatformToolset=v145 /p:OutDir=${{ github.workspace }}\build
      if: matrix.tool != 'libdvdread'

    - name: Build tool
      run: msbuild '${{ matrix.tool }}/SMP/${{ matrix.tool }}.sln' /p:configuration=ReleaseDLL /p:platform=x64 /p:PlatformToolset=v145 /p:OutDir=${{ github.workspace }}\build

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.tool }}
        path: ${{ github.workspace }}/msvc

