name: Build pydvdread wheels for Windows
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_pydvdread:
    name: Build pydvdread
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]

    steps:
    - name: Get latest libdvdread build
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: ShiftMediaProject
        repo: libdvdread

    - name: Download libvdread
      run: Invoke-WebRequest -Uri https://github.com/ShiftMediaProject/libdvdread/releases/download/6.1.3-1/libdvdread_6.1.3-1_msvc17.zip -OutFile c:\build\libdvdread.zip

    - name: Unpack libdvdread
      run: Expand-Archive -Path c:\build\libdvdread.zip -DestinationPath c:\build\libdvdread

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools
      run: pip3 install -U setuptools

    - name: Setup dev cmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Python wheel
      working-directory: c:\build\libdvdread
      run: pip3 wheel https://github.com/noah1510/PyDvdRead

    - uses: actions/upload-artifact@v4
      with:
        name: net-snmp-wheels Python ${{ matrix.python-version }}
        path: dist

