name: Build custom FFmpeg for windows
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_ffmpeg:
    runs-on: windows-2025
    steps:

    - name: Checkout FFmpeg
      uses: actions/checkout@v5
      with:
        repository: ShiftMediaProject/FFmpeg
        path: ${{ github.workspace }}/build/FFmpeg

    - name: Checkout libdvdnav
      uses: actions/checkout@v5
      with:
        repository: ShiftMediaProject/libdvdnav
        path: ${{ github.workspace }}/build/dvdnav

    - name: Get dependencies
      run: SMP/project_get_dependencies.bat
      working-directory: ${{ github.workspace }}/build/FFmpeg

    - name: Download FFVS-Project-Generator
      run: Invoke-WebRequest -Uri https://github.com/ShiftMediaProject/FFVS-Project-Generator/releases/download/1.12.0/FFVS-Project-Generator_1.12.0_x64.zip -OutFile FFVS-Project-Generator.zip

    - name: Unpack FFVS-Project-Generator
      run: Expand-Archive -Path FFVS-Project-Generator.zip -DestinationPath ${{ github.workspace }}/build/FFVS-Project-Generator

    - run: dir ${{ github.workspace }}/build

    - name: Generate FFmpeg project
      shell: cmd
      run: project_generate.exe --enable-gpl --enable-version3 --enable-libbluray --enable-libdvdnav --enable-libdvdread --disable-nvdec --disable-nvenc
      working-directory: ${{ github.workspace }}/build/FFVS-Project-Generator

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2 # Action to set up MSBuild environment

    - name: Build dependencies
      run: msbuild 'SMP/ffmpeg_deps.sln' /p:configuration=Release /p:platform=x64
      working-directory: ${{ github.workspace }}/build/FFmpeg

    - name: Build FFmpeg
      run: msbuild 'SMP/ffmpeg.sln' /p:configuration=Release /p:platform=x64
      working-directory: ${{ github.workspace }}/build/FFmpeg

    - uses: actions/upload-artifact@v4
      with:
        name: ffmpeg
        path: ${{ github.workspace }}/msvc # ${{ github.workspace }}/../../msvc
